########################################################################
###                                                                  ###
###                        Sqoop                                     ###
###                                                                  ###
########################################################################


sqoop:
  deployment:
    name: sqoop
    image:
      repository: soloio/sqoop
      pullPolicy: Always
    proxy:
      tag: 0.14.1
      repository: quay.io/solo-io/gloo-envoy-wrapper
      pullPolicy: Always
  service:
    port: 9095
    name: sqoop
  configMap:
    name: sqoop-proxy-config
